version: '3.8'

services:
  sports-updater:
    build: .
    container_name: sports-updater-nas
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Persistance des fichiers JSON générés
      - ./output:/app/output
    networks:
      - sports-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  sports-network:
    driver: bridge
